from src.selector.base import SolverSelector, NaiveSelector, RandomSelector, OracleSelector
from src.selector.embedding_ml import EmbeddingMLMultiTargetRegressionSelector, EmbeddingMLAccBinaryRegressionSelector
from src.selector.embedding_ml import EmbeddingMLTreeMultiRegressionSelector, EmbeddingMLTreeAccBinaryRegressionSelector
from src.selector.embedding_ml import EmbeddingMLClassificationSelector
from src.selector.embedding_retrieval import EmbeddingBasedRetrivalSelector